server:
  port: 8080
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&netTimeoutForStreamingResults=0&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


#mytabis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.demo.entity
  global-config:
    db-config:
      id-type: 2
      field-strategy: 2
      table-underline: true
logging:
  config: classpath:logback-file.xml
  level:
    com.demo.mapper: debug
logback:
  logFileDir: /data/logs/demo
  logFile: demo